### ISSUE TITLE
hi. is it possible to execute on 

### ISSUE THREAD

**Issue by serlogo53** [stefanvangastel/CakePHP-Labelprinting#1]
is it possible to execute on xampp?  i couldn t print. can you help please..

**Comment by stefanvangastel** [comment]
What does your (error)log say?

**Comment by serlogo53** [comment]
Hi stefan,

Thanks for your forward. İn this morning i fixed. Firewall blocked writes.
When i send data nothing do. Now fixed. Thanks.

Best regards.
